defmodule Zee3.StdLib.FiniteSet do
  @moduledoc """
  Implementation of a custom finite set objecte on top of existing theories.
  """
  require Zee3
  alias Zee3.Smt2

  # A set of size 10^6 is probably larger than Z3 could ever handle
  # in practice using this architecture, so it is a safe limit.
  # Having a fixed limit makes it much easier to extract the sets
  # from a model.

  @pad_length 6

  @typedoc """
  A type for a `FiniteSet`, for use inside a `Zee3.program`.
  This should not be used inside normal Elixir code.
  This module contains functionality to extract these sets
  from the Zee3 model into elixir `MapSet`s.
  """
  @type t() :: %__MODULE__{
    name: binary(),
    slots: list(Smt2.t()),
    cardinality: Smt2.t(),
    max_size: integer()
  }

  @derive {Inspect, only: [:name]}

  defstruct name: nil,
            slots: nil,
            cardinality: nil,
            max_size: nil

  @doc """
  Declare a new finite set.

  This will return a `#Zee3.StdLib.FiniteSet<...>`, which can
  be used as an argument to the functions in this module.
  This struct contains a `:cardinality` field (`set.cardinality`)
  which can be used as a constant inside the Zee3 program.
  This can be used to assert facts about the cardinality, which
  is just a normal integer constant inside Zee3.

  Note that this function *does not* declare a normal Z3 constant
  which is a set. That is not possible, because Z3 doesn't support
  a theory of finite sets. Instead, this function declares a number
  of constants and constraints between them in such a way that the
  normal axioms of set theory will work.
  """
  @spec declare(pid(), binary(), Sort.t(), [max_size: integer()]) :: t()
  def declare(pid \\ Zee3.current_z3_pid!(), name, element_type, args) do
    max_size = Keyword.fetch!(args, :max_size)

    Zee3.program pid do
      slots =
        for j <- 0..(max_size - 1) do
          # Pad the number with zeros so we can sort these alphabetically
          declare_const("__set_slot_#{pad(j)}__#{name}", element_type)
        end

      cardinality = declare_const("__set_cardinality__#{name}", Sort.int())

      assert cardinality >= 0
      assert cardinality <= max_size

      for i <- 0..(max_size - 1) do
        for j <- min(i + 1, max_size - 1)..(max_size - 1), i != j do
          assert implies(cardinality > j, Enum.at(slots, i) != Enum.at(slots, j))
        end
      end

      %__MODULE__{
        name: name,
        slots: slots,
        cardinality: cardinality,
        max_size: max_size
      }
    end
  end

  defp pad(n) do
    String.pad_leading(to_string(n), @pad_length, "0")
  end

  @doc """
  Checks that the set contains an element.
  """
  @spec contains(t(), Smt2.smt2_like()) :: Smt2.t()
  def contains(%__MODULE__{} = set, element) do
    use Zee3.StdLib

    conditions =
      for i <- elixir(0..(set.max_size - 1)) do
        set.cardinality > i and Enum.at(set.slots, i) == element
      end

    any(conditions)
  end

  @doc """
  Checks that the set on the LHS is a subset of the set on the RHS
  """
  @spec subset_of(t(), t()) :: Smt2.t()
  def subset_of(%__MODULE__{} = set_a, %__MODULE__{} = set_b) do
    use Zee3.StdLib

    conditions =
      for i <- elixir(0..(set_a.max_size - 1)) do
        elem_a = Enum.at(set_a.slots, i)
        implies(set_a.cardinality > i, contains(set_b, elem_a))
      end

    all([set_a.cardinality <= set_b.cardinality | conditions])
  end

  @doc """
  Checks that the set on the LHS is a superset of the set on the RHS
  """
  @spec superset_of(t(), t()) :: Smt2.t()
  def superset_of(%__MODULE__{} = set_a, %__MODULE__{} = set_b) do
    subset_of(set_b, set_a)
  end

  @doc """
  Checks the sets contain exactly the same elements.
  """
  @spec equal(t(), t()) :: Smt2.t()
  def equal(%__MODULE__{} = set_a, %__MODULE__{} = set_b) do
    use Zee3.StdLib

    subset_of(set_a, set_b) and subset_of(set_b, set_a)
  end

  @doc """
  Checks that the sets are disjoint (i.e. they share no elements in common)
  """
  @spec disjoint(t(), t()) :: Smt2.t()
  def disjoint(%__MODULE__{} = set_a, %__MODULE__{} = set_b) do
    use Zee3.StdLib

    conditions =
      for i <- elixir(0..(set_a.max_size - 1)), j <- elixir(0..(set_b.max_size - 1)) do
        both_active = set_a.cardinality > i and set_b.cardinality > j
        implies(both_active, Enum.at(set_a.slots, i) != Enum.at(set_b.slots, j))
      end

    all(conditions)
  end

  @doc """
  Extracts Z3 finite sets from a model map into Elixir `MapSet`s.

  Expects slot keys in the format `__set_slot_000000__set_name`,
  which is the format generated by the set declaration functions.
  """
  @spec extract_all_from_model(map()) :: %{binary() => MapSet.t()}
  def extract_all_from_model(%{} = model) do
    model
    # Phase 1: Single pass to group slots and cardinality
    |> Enum.reduce(%{}, fn
      # Clause 1: Match Cardinality
      {"__set_cardinality__" <> set_name, card}, acc ->
        update_in(acc, [Access.key(set_name, %{cardinality: 0, slots: %{}})], &%{&1 | cardinality: card})

      # Clause 2: Match Slot (Notice the corrected { } tuple brackets)
      {<<"__set_slot_", index_str::binary-size(6), "__", set_name::binary>>, value}, acc ->
        index = String.to_integer(index_str)

        update_in(acc, [Access.key(set_name, %{cardinality: 0, slots: %{}})], fn state ->
          put_in(state.slots[index], value)
        end)

      # Clause 3: Ignore extraneous variables
      _extraneous, acc ->
        acc
    end)
    # Phase 2: Convert to MapSets using the cardinality bound
    |> Map.new(fn {set_name, data} ->
      dbg(data)
      # 0..-1//1 safely creates an empty range if cardinality is 0
      elements =
        0..(data.cardinality - 1)//1
        |> Enum.map(fn i ->
          Map.get(data.slots, i)
        end)

      {set_name, MapSet.new(elements)}
    end)
  end

  @doc """
  Extracts a single Z3 finite set from a model map into an Elixir `MapSet`.
  Returns either `{:ok, MapSet.new([...])}` or `:error` if the set does
  not exist.

  Expects slot keys in the format `__set_slot_000000__set_name`,
  which is the format generated by the set declaration functions.
  """
  @spec extract_from_model(map(), binary()) :: {:ok, MapSet.t()} | :error
  def extract_from_model(model = %{}, set_name) do
    cardinality_key = "__set_cardinality__" <> set_name

    case Map.get(model, cardinality_key) do
      # If the set exists and has elements
      card when is_integer(card) and card > 0 ->
        elements =
          0..(card - 1)//1
          |> Enum.map(fn i ->
            # Reconstruct the exact padded 6-digit key
            index_str = i |> Integer.to_string() |> String.pad_leading(6, "0")
            slot_key = "__set_slot_" <> index_str <> "__" <> set_name

            # Direct lookup is extremely fast
            Map.get(model, slot_key)
          end)

        {:ok, MapSet.new(elements)}

      # If the set exists but doesn't have elements (empty set)
      card when is_integer(card) and card == 0 ->
        {:ok, MapSet.new([])}

      # If the cardinality is 0 or the set_name doesn't exist in the model
      _ ->
        :error
    end
  end

  @doc """
  Extracts a single Z3 finite set from a model map into an Elixir `MapSet`.
  Raises on error.

  Expects slot keys in the format `__set_slot_000000__set_name`,
  which is the format generated by the set declaration functions.
  """
  @spec extract_from_model!(map(), binary()) :: MapSet.t()
  def extract_from_model!(model = %{}, set_name) do
    case extract_from_model(model, set_name) do
      {:ok, set} -> set
      :error -> raise "Set with the name '#{set_name}' does not exist."
    end
  end
end
